/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type ProjectReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "project";
};

export type Fraction = {
  _id: string;
  _type: "fraction";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  identifier?: string;
  project?: ProjectReference;
  reference?: LocalizedString;
  type?: "apartment" | "house" | "shop" | "office";
  typology?: "T0" | "T1" | "T2" | "T3" | "T4" | "T5";
  status?: "available" | "reserved" | "sold";
  floor?: LocalizedString;
  grossArea?: number;
  usefulArea?: number;
  energyCertificate?: string;
  features?: LocalizedStringArray;
  description?: LocalizedText;
  floorPlan?: ProjectImage;
  images?: Array<
    {
      _key: string;
    } & ProjectImage
  >;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ProjectImage = {
  _type: "projectImage";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: LocalizedString;
};

export type LocalizedText = {
  _type: "localizedText";
  pt?: string;
  en?: string;
};

export type LocalizedStringArray = {
  _type: "localizedStringArray";
  pt?: Array<string>;
  en?: Array<string>;
};

export type LocalizedString = {
  _type: "localizedString";
  pt?: string;
  en?: string;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  location?: LocalizedString;
  description?: LocalizedText;
  status?: "planning" | "under_construction" | "completed";
  completionDate?: string;
  features?: LocalizedStringArray;
  images?: Array<
    {
      _key: string;
    } & ProjectImage
  >;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | ProjectReference
  | Fraction
  | SanityImageAssetReference
  | ProjectImage
  | LocalizedText
  | LocalizedStringArray
  | LocalizedString
  | Project
  | Slug
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../fracao-ilustre-website/src/sanity/queries.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project" && defined(slug.current)] | order(completionDate desc) {    _id,    title,    "slug": slug.current,    location,    description,    status,    completionDate,    features,    images[] {      _key,      asset-> {        _id,        url      },      alt,      hotspot,      crop    }  }
export type PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  location: LocalizedString | null;
  description: LocalizedText | null;
  status: "completed" | "planning" | "under_construction" | null;
  completionDate: string | null;
  features: LocalizedStringArray | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
    alt: LocalizedString | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  }> | null;
}>;

// Source: ../fracao-ilustre-website/src/sanity/queries.ts
// Variable: PROJECT_BY_SLUG_QUERY
// Query: *[_type == "project" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    location,    description,    status,    completionDate,    features,    images[] {      _key,      asset-> {        _id,        url      },      alt,      hotspot,      crop    }  }
export type PROJECT_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  location: LocalizedString | null;
  description: LocalizedText | null;
  status: "completed" | "planning" | "under_construction" | null;
  completionDate: string | null;
  features: LocalizedStringArray | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
    alt: LocalizedString | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  }> | null;
} | null;

// Source: ../fracao-ilustre-website/src/sanity/queries.ts
// Variable: FRACTIONS_QUERY
// Query: *[_type == "fraction"] | order(_createdAt asc) {    _id,    "id": identifier,    "projectSlug": project->slug.current,    reference,    type,    typology,    status,    floor,    grossArea,    usefulArea,    energyCertificate,    features,    description,    floorPlan {      asset-> {        _id,        url      },      alt,      hotspot,      crop    },    images[] {      _key,      asset-> {        _id,        url      },      alt,      hotspot,      crop    }  }
export type FRACTIONS_QUERY_RESULT = Array<{
  _id: string;
  id: string | null;
  projectSlug: string | null;
  reference: LocalizedString | null;
  type: "apartment" | "house" | "office" | "shop" | null;
  typology: "T0" | "T1" | "T2" | "T3" | "T4" | "T5" | null;
  status: "available" | "reserved" | "sold" | null;
  floor: LocalizedString | null;
  grossArea: number | null;
  usefulArea: number | null;
  energyCertificate: string | null;
  features: LocalizedStringArray | null;
  description: LocalizedText | null;
  floorPlan: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
    alt: LocalizedString | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
    alt: LocalizedString | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  }> | null;
}>;

// Source: ../fracao-ilustre-website/src/sanity/queries.ts
// Variable: FRACTION_BY_ID_QUERY
// Query: *[_type == "fraction" && identifier == $id][0] {    _id,    "id": identifier,    "projectSlug": project->slug.current,    reference,    type,    typology,    status,    floor,    grossArea,    usefulArea,    energyCertificate,    features,    description,    floorPlan {      asset-> {        _id,        url      },      alt,      hotspot,      crop    },    images[] {      _key,      asset-> {        _id,        url      },      alt,      hotspot,      crop    }  }
export type FRACTION_BY_ID_QUERY_RESULT = {
  _id: string;
  id: string | null;
  projectSlug: string | null;
  reference: LocalizedString | null;
  type: "apartment" | "house" | "office" | "shop" | null;
  typology: "T0" | "T1" | "T2" | "T3" | "T4" | "T5" | null;
  status: "available" | "reserved" | "sold" | null;
  floor: LocalizedString | null;
  grossArea: number | null;
  usefulArea: number | null;
  energyCertificate: string | null;
  features: LocalizedStringArray | null;
  description: LocalizedText | null;
  floorPlan: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
    alt: LocalizedString | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
    alt: LocalizedString | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  }> | null;
} | null;

// Query TypeMap
declare global {
  interface SanityQueries {
    '\n  *[_type == "project" && defined(slug.current)] | order(completionDate desc) {\n    _id,\n    title,\n    "slug": slug.current,\n    location,\n    description,\n    status,\n    completionDate,\n    features,\n    images[] {\n      _key,\n      asset-> {\n        _id,\n        url\n      },\n      alt,\n      hotspot,\n      crop\n    }\n  }\n': PROJECTS_QUERY_RESULT;
    '\n  *[_type == "project" && slug.current == $slug][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    location,\n    description,\n    status,\n    completionDate,\n    features,\n    images[] {\n      _key,\n      asset-> {\n        _id,\n        url\n      },\n      alt,\n      hotspot,\n      crop\n    }\n  }\n': PROJECT_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "fraction"] | order(_createdAt asc) {\n    _id,\n    "id": identifier,\n    "projectSlug": project->slug.current,\n    reference,\n    type,\n    typology,\n    status,\n    floor,\n    grossArea,\n    usefulArea,\n    energyCertificate,\n    features,\n    description,\n    floorPlan {\n      asset-> {\n        _id,\n        url\n      },\n      alt,\n      hotspot,\n      crop\n    },\n    images[] {\n      _key,\n      asset-> {\n        _id,\n        url\n      },\n      alt,\n      hotspot,\n      crop\n    }\n  }\n': FRACTIONS_QUERY_RESULT;
    '\n  *[_type == "fraction" && identifier == $id][0] {\n    _id,\n    "id": identifier,\n    "projectSlug": project->slug.current,\n    reference,\n    type,\n    typology,\n    status,\n    floor,\n    grossArea,\n    usefulArea,\n    energyCertificate,\n    features,\n    description,\n    floorPlan {\n      asset-> {\n        _id,\n        url\n      },\n      alt,\n      hotspot,\n      crop\n    },\n    images[] {\n      _key,\n      asset-> {\n        _id,\n        url\n      },\n      alt,\n      hotspot,\n      crop\n    }\n  }\n': FRACTION_BY_ID_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
